export const APP_STATUS_HTTP = Object.freeze({
  SUCCESS: 200,
  BAD_REQUEST: 400,
  SERVER_INTERNAL: 500,
  ACCESS_DENIED: 401,
  NOT_FOUND: 404,
});

export const APP_LIST_STATUS_ERROR = [
  APP_STATUS_HTTP.BAD_REQUEST,
  APP_STATUS_HTTP.NOT_FOUND,
  APP_STATUS_HTTP.ACCESS_DENIED,
  APP_STATUS_HTTP.SERVER_INTERNAL,
] as number[];
